### PR TITLE
support other gallery properties

### PR DESCRIPTION
**Pull request by vwxyzjn**
This PR supports other gallery properties such as tag and text. See the following for a demo

image

Had to mess with the CSS to make it not look like the following:

image

Another behavior change is that, *instead of using the whole card as link to the notion page*, only the cover is linked to the notion page. Perhaps this behavior is not desirable with card that has no cover, but my ability is limited in making this general as I am sure I am misusing `visibleColumns.map(col => {... }`.

### CODE REVIEW

**Comment by vwxyzjn** [comment]
See https://github.com/vwxyzjn/notablog-starter/tree/c2ad745851e9c2dd0ecd114f3fb677b91f7fb2ce as an example for the css

**Comment by dragonman225** [comment]
Hi, your screenshot looks promising, but I could not reproduce the result.

image

I used your repo (https://github.com/vwxyzjn/nast) and the CSS you provided (https://github.com/vwxyzjn/notablog-starter/blob/c2ad745851e9c2dd0ecd114f3fb677b91f7fb2ce/themes/pure/assets/css/theme.css), to see if the rendering library itself works well (without the interference of Notablog), but I was unable to get the same result as yours. My browser is Chrome 80.0.3987.149.

Did I miss anything or are there any changes not included in your repo?

Also, more information about the testing method can be found here (https://github.com/dragonman225/nast#testing).

**Comment by vwxyzjn** [comment]
Hi, were you able to reproduce the following?

```
git clone https://github.com/vwxyzjn/notablog-starter.git && cd notablog-starter
npm i -g vwxyzjn_notablog
notablog generate .
bash posthook.sh
notablog preview .
```

I used the command above to generate https://costa.sh. The build actually happens in the netlify, so I would imagine it will also work for you

**Comment by vwxyzjn** [comment]
image


This is the error that I had

**Comment by dragonman225** [comment]
> Hi, were you able to reproduce the following?
> 
> ```
> git clone https://github.com/vwxyzjn/notablog-starter.git && cd notablog-starter
> npm i -g vwxyzjn_notablog
> notablog generate .
> bash posthook.sh
> notablog preview .
> ```
> 
> I used the command above to generate https://costa.sh. The build actually happens in the netlify, so I would imagine it will also work for you

It works and the gallery looks good. I also tried deleting `notablog.css` and `SourceSansPro.css` but keep `theme.css` in `css/` directory of the generated site, the gallery still looks good. Not sure what cause the difference, I will need to investigate further.

**Comment by dragonman225** [comment]
> image
> 
> This is the error that I had

Before running `node packages/npdl/index.js ...`, `nast-util-from-notionapi`, `nast-util-to-html`, `nast-util-to-react`, and `notion-util` have to be built first (compiled from TypeScript to JavaScript).

You can `cd` into those packages and issue `npm run build`

```bash
cd packages/<package_name>
npm run build
```

Or use [this script](https://github.com/dragonman225/nast/blob/master/bootstrap.sh) to automate the procedure.

**Comment by vwxyzjn** [comment]
Although I get errors like the following, I could reproduce your results, I will also dig a little into it.


```
(base) [costa@costa-pc nast]$ sudo bash bootstrap.sh 
lerna notice cli v3.20.2
lerna info versioning independent
lerna info Bootstrapping 7 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 7 packages
/home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-from-notionapi /home/costa/Documents/work/go/src/github.com/111/nast

> nast-util-from-notionapi@1.0.1 build /home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-from-notionapi
> npm run build:module && npm run build:doc


> nast-util-from-notionapi@1.0.1 build:module /home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-from-notionapi
> rm -rf dist && rollup -c && tsc --emitDeclarationOnly


src/index.ts → dist/index.js, dist/index.esm.js...
created dist/index.js, dist/index.esm.js in 372ms
src/transformCollection.ts:46:7 - error TS2739: Type 'never[]' is missing the following properties from type '{ filters: Filter2[]; operator: FilterOperator; }': filters, operator

46       filter: [],
         ~~~~~~

  node_modules/notionapi-agent/dist/interfaces/notion-models/collection-view/query.d.ts:27:3
    27   filter: {
         ~~~~~~
    The expected type comes from property 'filter' which is declared here on type 'Query2'

src/transformCollection.ts:54:5 - error TS2571: Object is of type 'unknown'.

54     Object.values(queryResult.recordMap.collection)[0].value
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nast-util-from-notionapi@1.0.1 build:module: `rm -rf dist && rollup -c && tsc --emitDeclarationOnly`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nast-util-from-notionapi@1.0.1 build:module script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-30T02_08_07_490Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nast-util-from-notionapi@1.0.1 build: `npm run build:module && npm run build:doc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nast-util-from-notionapi@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-30T02_08_07_500Z-debug.log
/home/costa/Documents/work/go/src/github.com/111/nast
/home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-to-html /home/costa/Documents/work/go/src/github.com/111/nast

> nast-util-to-html@0.2.8 build /home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-to-html
> npm run build:module && npm run build:doc


> nast-util-to-html@0.2.8 build:module /home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-to-html
> rm -rf dist && rollup -c && tsc --emitDeclarationOnly


src/index.ts → dist/index.js, dist/index.esm.js...
(!) Circular dependency
src/util.ts -> src/util-prismjs.ts -> src/util.ts
created dist/index.js, dist/index.esm.js in 410ms

> nast-util-to-html@0.2.8 build:doc /home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-to-html
> npm run build:typedoc && npm run build:dependency-graph


> nast-util-to-html@0.2.8 build:typedoc /home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-to-html
> typedoc --out typedoc --mode file src/

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/lib/node_modules/typedoc/dist/lib/cli.js
- /usr/lib/node_modules/typedoc/bin/typedoc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/typedoc/dist/lib/cli.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/typedoc/dist/lib/cli.js',
    '/usr/lib/node_modules/typedoc/bin/typedoc'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nast-util-to-html@0.2.8 build:typedoc: `typedoc --out typedoc --mode file src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nast-util-to-html@0.2.8 build:typedoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-30T02_08_09_700Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nast-util-to-html@0.2.8 build:doc: `npm run build:typedoc && npm run build:dependency-graph`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nast-util-to-html@0.2.8 build:doc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-30T02_08_09_711Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nast-util-to-html@0.2.8 build: `npm run build:module && npm run build:doc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nast-util-to-html@0.2.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-30T02_08_09_720Z-debug.log
/home/costa/Documents/work/go/src/github.com/111/nast
/home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-to-react /home/costa/Documents/work/go/src/github.com/111/nast

> nast-util-to-react@1.0.2 build /home/costa/Documents/work/go/src/github.com/111/nast/packages/nast-util-to-react
> rm -rf dist && rollup -c && tsc --emitDeclarationOnly


src/index.tsx → dist/index.js, dist/index.esm.js...
created dist/index.js, dist/index.esm.js in 581ms
/home/costa/Documents/work/go/src/github.com/111/nast
/home/costa/Documents/work/go/src/github.com/111/nast/packages/notion-util /home/costa/Documents/work/go/src/github.com/111/nast

> notion-util@1.0.0 build /home/costa/Documents/work/go/src/github.com/111/nast/packages/notion-util
> tsc && tsc --emitDeclarationOnly

/home/costa/Documents/work/go/src/github.com/111/nast
```

**Comment by vwxyzjn** [comment]
It seems to be a bug on the npdl side. So I removed all of my changes and ran with the original package, and this is what I got

image

**Comment by vwxyzjn** [comment]
Ok a really quick fix would be to change the css for gallery item cover:

```
.Gallery__Item__Cover {
  box-shadow: rgba(55, 53, 47, 0.09) 0px -1px 0px 0px inset;
  height: 150px;
}
```
And it works as shown below, but I am not sure of the reason. Essentailly the cover was somehow calculated to have height of 0.xx px.
image

**Comment by dragonman225** [comment]
> Ok a really quick fix would be to change the css for gallery item cover:
> 
> ```css
> .Gallery__Item__Cover {
>   box-shadow: rgba(55, 53, 47, 0.09) 0px -1px 0px 0px inset;
>   height: 150px;
> }
> ```

Thanks! It looks great!

Would you mind changing the `height` to `200px`? Since the image inside the `.Gallery__Item__Cover` may be up to 200px tall.

```css
.Gallery__Item__Cover>img {
    width: 100%;
    height: 100%;
    max-height: 200px;
    border-radius: 5px 5px 0 0;
    object-fit: cover;
    object-position: center 50%;
    padding-bottom: 1px;
}
```

By the way, I notice that the renderer would crash if there are **Checkbox** properties or **Created time / Last edited time** properties in the gallery ([here's a Notion page](https://www.notion.so/Complex-Block-Test-fea7afd4dede4e74954935c9c23f515b) for testing), and that's because in [this](https://github.com/vwxyzjn/nast/blob/c0147680f7c0b9182638b4abd44c8adb224f963f/packages/nast-util-to-react/src/components/Collection.tsx#L334) `switch ... case ...` block, you do not handle `case "checkbox"`, `case "created_time"`, `case "last_edited_time"`, `case "created_by"`, and `case "last_edited_by"`.
Instead, they are passed to the default case,

```ts
default:
    return (
       <div className={`${elemNameBase}Text`}>
           <SemanticStringArray semanticStringArray={data.value as NAST.SemanticString[]} />
       </div>
    )
```

where the `<SemanticStringArray>` component cannot accept boolean (`data.value`'s type for "checkbox"), number (`data.value`'s type for "created_time" and "last_edited_time"), and string (`data.type`'s type for "created_by" and "last_edited_by").

If don't know how to correctly handle them, you could just add

```ts
case "checkbox":
case "created_by":
case "last_edited_by":
case "created_time":
case "last_edited_time":
   return <></> // An empty React.Fragment, which renders to nothing.
```

Once again, thank you for investing time on contributing to this project!

**Comment by vwxyzjn** [comment]
image

Hmm probably doesn't support gallery items without covers... but everything else is fixed.

**Comment by vwxyzjn** [comment]
Thanks for the comments.

**Comment by dragonman225** [comment]
> image
> 
> Hmm probably doesn't support gallery items without covers... but everything else is fixed.

This works as expected, Notion renders gallery items without covers like this, too, if you take a look a [the Notion page](https://www.notion.so/Complex-Block-Test-fea7afd4dede4e74954935c9c23f515b).

**Comment by dragonman225** [comment]
I merged your commits manually so that I could edit the commit messages to make them easier to be associated with the `nast-util-to-react` sub-project. See https://github.com/dragonman225/nast/commits/master for the result.
Actually, I should have written a contributing guideline.
All in all, thank you for the contribution.

**Comment by vwxyzjn** [comment]
Thank you for the great work too. Much appreciated.

**Pull request closed without merging**
